language: python
python:
  - 3.5
  - 3.6
  - 2.7

script: py.test

notifications:
  email:
    on_success: never
    on_failure: never

deploy:
  provider: pypi
  user: wesyoung
  password:
    secure: NHN/ckmXdR/g15AnC5/wA4VWLIODfAR4DY0mr4qajxIAvts83hlB/LNvcEKpN57RUUOt4H8sX4qsLZCdxWpEQfBENxGSazCQYgl91Mi3J5FB9LS6WLVkh691hxEjvcK8XMYPvd+DVhx+Nu6Ew8fyoOk2+slJ1gWFdpkYLFzyP4I=
  on:
    branch: master
    tags: true
